# Meta Data for SEO

## Homepage
title = "piglatin.app"
titleSeparator = "-"
titleAddition = "A simple translation app"
description = "Piglatin.app is a simple application that translates plain text to pig-latin"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "tbutler0x90"
twitterCreator = "tbutler0x90"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/tbutler0x90"
schemaLinkedIn = "https://www.linkedin.com/in/tyler-b-a700a1aa/"
schemaGitHub = "https://github.com/tcbutler320"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Created by Tyler Butler | Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Piglatin.app? <a class=\"alert-link\" href=\"https://github.com/tcbutler320/piglatin.app\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/tcbutler320/piglatin.app"
editPage = false
