# Meta Data for SEO

## Homepage
title = "JPigLatin"
titleSeparator = "-"
titleAddition = "A Simple JavaScript Translation and Speech Synthesis Application"
description = "JPigLatin is a Simple JavaScript Translation and Speech Synthesis Application"

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "tbutler0x90"
twitterCreator = "tbutler0x90"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/tbutler0x90"
schemaLinkedIn = "https://www.linkedin.com/in/tyler-b-a700a1aa/"
schemaGitHub = "https://github.com/tcbutler320"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Created by <a href=\"https://www.tbutler.org/\">Tyler Butler</a> <a href=\"https://www.github.com/tcbutler320/\"><i class=\"ri-github-fill\"></i></a> <a href=\"https://www.linkedin.com/in/tyler-b-a700a1aa//\"><i class=\"ri-linkedin-box-fill\"></i></a> <a href=\"https://twitter.com/tbutler0x90\"><i class=\"ri-twitter-fill\"></i></a>| <span class=\"pull-right\">Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a></span>"

# Alert
alert = false
alertText = "Like Piglatin.app? <a class=\"alert-link\" href=\"https://github.com/tcbutler320/piglatin.app\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/tcbutler320/piglatin.app"
editPage = false
